name: "tagged-release"

on: 
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number, like : v1.0'     
        required: true

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "windows-latest"

    steps:
      - uses: actions/checkout@v2
      - name: "Build"
        run: .\make.ps1
        shell: pwsh

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ github.event.inputs.version }}"
          prerelease: false
          files: |
            build/*
